import { Schema, model, Document, Types } from 'mongoose';

export interface IMedicalHistory extends Document {
  userId: Types.ObjectId;
  allergies: string[];
  activeMedications: Array<{
    name: string;
    prescribedDate: Date;
    prescriptionId: Types.ObjectId;
  }>;
  chronicConditions: string[];
  healthSummary: string; // A text summary generated by AI for the Chatbot
  lastUpdated: Date;
}

const medicalHistorySchema = new Schema<IMedicalHistory>({
  userId: { type: Schema.Types.ObjectId, ref: 'User', unique: true, required: true },
  allergies: { type: [String], default: [] },
  activeMedications: [{
    name: String,
    prescribedDate: { type: Date, default: Date.now },
    prescriptionId: { type: Schema.Types.ObjectId, ref: 'Prescription' }
  }],
  chronicConditions: { type: [String], default: [] },
  healthSummary: { type: String, default: "" },
  lastUpdated: { type: Date, default: Date.now }
});

export const MedicalHistory = model<IMedicalHistory>('MedicalHistory', medicalHistorySchema);